=== msmantri55/class/cs373/5/Faculty1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="faculty_members" type="faculty_members_type"/>

	<xs:complexType name="faculty_members_type">
		<xs:sequence>
			<xs:element name="faculty_member" type="faculty_member_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="faculty_member_type">
		<xs:all>
			<xs:element name="name" type="name_type"/>
			<xs:element name="username" type="username_type" minOccurs="0"/>
			<xs:element name="faculty_type" type="xs:normalizedString"/>
			<xs:element name="office" type="location_type"/>
			<xs:element name="email_addresses" type="email_addresses_type"/>
			<xs:element name="websites" type="websites_type" minOccurs="0"/>
			<xs:element name="phone_numbers" type="phone_numbers_type" minOccurs="0"/>
			<xs:element name="research_areas" type="research_areas_type" minOccurs="0"/>
			<xs:element name="degrees" type="degrees_type" minOccurs="0"/>
			<xs:element name="awards" type="awards_type" minOccurs="0"/>
			<xs:element name="office_hours" type="meeting_times_and_places_type" minOccurs="0"/>
			<xs:element name="classes" type="classes_type" minOccurs="0"/>
			<xs:element name="published_books" type="published_books_type" minOccurs="0"/>
			<xs:element name="journal_articles" type="journal_articles_type" minOccurs="0"/>
			<xs:element name="conferences" type="conferences_type" minOccurs="0"/>
			<xs:element name="grad_students" type="grad_students_type" minOccurs="0"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="name_type">
		<xs:all>
			<xs:element name="first_name" type="xs:normalizedString"/>
			<xs:element name="middle_name" type="xs:normalizedString" minOccurs="0"/>
			<xs:element name="last_name" type="xs:normalizedString"/>
			<xs:element name="suffix" type="xs:normalizedString" minOccurs="0"/>
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="username_type">
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="[a-z_][a-z0-9_-]*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="location_type">
		<xs:all>
			<xs:element name="building" type="building_type"/>
			<xs:element name="room" type="xs:normalizedString"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="building_type">
		<xs:all>
			<xs:element name="abbreviation" type="building_abbreviation_type"/>
			<xs:element name="long_name" type="xs:normalizedString"/>
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="building_abbreviation_type">
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="[A-Z]{2,5}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="email_addresses_type">
		<xs:sequence>
			<xs:element name="email" type="email_type" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="email_type">
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="[a-z0-9!#$%&amp;'*+/=?^_`{|}~-]+(\.[a-z0-9!#$%&amp;'*+/=?^_`{|}~-]+)*@([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+([A-Z]{2}|edu|com|org|net|gov|mil|biz|info|mobi|name|aero|jobs|museum)"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="websites_type">
		<xs:sequence>
			<xs:element name="website" type="website_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="website_type">
		<xs:restriction base="xs:anyURI">
			<xs:pattern value="(http|https|shttp)://.*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="phone_numbers_type">
		<xs:sequence>
			<xs:element name="phone_number" type="phone_number_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="phone_number_type">
		<xs:all>
			<xs:element name="phone_type" type="phone_type_type"/>
			<xs:element name="country_code" type="country_code_type" minOccurs="0"/>
			<xs:element name="area_code" type="area_code_type" minOccurs="0"/>
			<xs:element name="number" type="number_type"/>
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="phone_type_type">
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="home"/>
			<xs:enumeration value="department"/>
			<xs:enumeration value="work"/>
			<xs:enumeration value="cell"/>
			<xs:enumeration value="fax"/>
			<xs:enumeration value="pager"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="country_code_type">
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="\d{1,3}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="area_code_type">
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="\d{3}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="number_type">
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="\d{7}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="research_areas_type">
		<xs:sequence>
			<xs:element name="research_area" type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="degrees_type">
		<xs:sequence>
			<xs:element name="degree" type="degree_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="degree_type">
		<xs:all>
			<xs:element name="date_awarded" type="xs:gYear"/>
			<xs:element name="institution" type="xs:normalizedString"/>
			<xs:element name="degree_type" type="xs:normalizedString"/>
			<xs:element name="specialization" type="xs:normalizedString" minOccurs="0"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="awards_type">
		<xs:sequence>
			<xs:element name="award" type="award_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="award_type">
		<xs:all>
			<xs:element name="name" type="xs:normalizedString"/>
			<xs:element name="date_awarded" type="xs:gYear"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="meeting_times_and_places_type">
		<xs:sequence>
			<xs:element name="meeting_time_and_place" type="meeting_time_and_place_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="meeting_time_and_place_type">
		<xs:all>
			<xs:element name="start_time" type="xs:time"/>
			<xs:element name="end_time" type="xs:time"/>
			<xs:element name="location" type="location_type"/>
			<xs:element name="days" type="days_type"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="days_type">
		<xs:sequence>
			<xs:element name="day" type="day_type" maxOccurs="5"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="day_type">
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="Monday"/>
			<xs:enumeration value="Tuesday"/>
			<xs:enumeration value="Wednesday"/>
			<xs:enumeration value="Thursday"/>
			<xs:enumeration value="Friday"/>
			<xs:enumeration value="Saturday"/>
			<xs:enumeration value="Sunday"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="classes_type">
		<xs:sequence>
			<xs:element name="class" type="class_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="class_type">
		<xs:all>
			<xs:element name="unique_number" type="unique_number_type"/>
			<xs:element name="name" type="xs:normalizedString"/>
			<xs:element name="description" type="xs:normalizedString"/>
			<xs:element name="course_number" type="course_number_type"/>
			<xs:element name="semester" type="semester_type"/>
			<xs:element name="year" type="xs:gYear"/>
			<xs:element name="teaching_assistants" type="names_type" minOccurs="0"/>
			<xs:element name="meeting_times_and_places" type="meeting_times_and_places_type"/>
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="unique_number_type">
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="\d{5}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="course_number_type">
		<xs:all>
			<xs:element name="field_of_study" type="field_of_study_type"/>
			<xs:element name="number" type="course_three_digit_number_type"/>
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="field_of_study_type">
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="[A-Z]{1,3}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="course_three_digit_number_type">
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="\d{3}[A-Z]?"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="semester_type">
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="Fall"/>
			<xs:enumeration value="Spring"/>
			<xs:enumeration value="Summer First Term"/>
			<xs:enumeration value="Summer Second Term"/>
			<xs:enumeration value="Summer Whole Term"/>
			<xs:enumeration value="Summer Nine Week Term"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="names_type">
		<xs:sequence>
			<xs:element name="name" type="name_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="published_books_type">
		<xs:sequence>
			<xs:element name="book" type="book_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="book_type">
		<xs:all>
			<xs:element name="title" type="xs:normalizedString"/>
			<xs:element name="publisher" type="xs:normalizedString"/>
			<xs:element name="date_published" type="xs:gYear"/>
			<xs:element name="other_authors" type="names_type" minOccurs="0"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="journal_articles_type">
		<xs:sequence>
			<xs:element name="article" type="article_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="article_type">
		<xs:all>
			<xs:element name="journal" type="xs:normalizedString"/>
			<xs:element name="title" type="xs:normalizedString"/>
			<xs:element name="issue_date" type="xs:gYearMonth"/>
			<xs:element name="other_authors" type="names_type" minOccurs="0"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="conferences_type">
		<xs:sequence>
			<xs:element name="conference" type="conference_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="conference_type">
		<xs:all>
			<xs:element name="date" type="xs:gYearMonth"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="location" type="xs:string"/>
			<xs:element name="presentation_title" type="xs:string"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="grad_students_type">
		<xs:sequence>
			<xs:element name="grad_student" type="grad_student_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="grad_student_type">
		<xs:all>
			<xs:element name="name" type="name_type"/>
			<xs:element name="type" type="grad_degree_type"/>
			<xs:element name="writings" type="grad_articles_type" minOccurs = "0"/>
			<xs:element name="date" type="xs:gYear" minOccurs = "0"/>
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="grad_degree_type">
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="Master's"/>
			<xs:enumeration value="Ph.D."/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="grad_articles_type">
		<xs:sequence>
			<xs:element name="writing" type="grad_article_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="grad_article_type">
		<xs:all>
			<xs:element name="type" type="writing_type"/>
			<xs:element name="journal" type="xs:normalizedString" minOccurs="0"/>
			<xs:element name="title" type="xs:normalizedString"/>
			<xs:element name="issue_date" type="xs:gYearMonth"/>
			<xs:element name="other_authors" type="names_type" minOccurs="0"/>
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="writing_type">
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="Thesis"/>
			<xs:enumeration value="Theses"/>
			<xs:enumeration value="Dissertation"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== msmantri55/class/cs373/5/Faculty1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<faculty_members xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Faculty1.xsd">
	<faculty_member> <!-- Lorenzo Alvisi -->
		<name>
			<first_name>Lorenzo</first_name>
			<last_name>Alvisi</last_name>
		</name>
		<username>lorenzo</username>
		<faculty_type>Professor</faculty_type>
		<office>
			<building>
				<abbreviation>ACES</abbreviation>
				<long_name>Applied Computational Engineering and Sciences Building</long_name>
			</building>
			<room>6.244</room>
		</office>
		<email_addresses>
			<email>lorenzo@cs.utexas.edu</email>
		</email_addresses>
		<websites>
			<website>http://userweb.cs.utexas.edu/~lorenzo/</website>
		</websites>
		<phone_numbers>
			<phone_number>
				<phone_type>work</phone_type>
				<country_code>1</country_code>
				<area_code>512</area_code>
				<number>4719792</number>
			</phone_number>
			<phone_number>
				<phone_type>fax</phone_type>
				<country_code>1</country_code>
				<area_code>512</area_code>
				<number>2327886</number>
			</phone_number>
		</phone_numbers>
		<research_areas>
			<research_area>Distributed Computing</research_area>
		</research_areas>
		<degrees>
			<degree>
				<date_awarded>1996</date_awarded>
				<institution>Cornell</institution>
				<degree_type>Ph.D.</degree_type>
				<specialization>Computer Science</specialization>
			</degree>
			<degree>
				<date_awarded>1994</date_awarded>
				<institution>Cornell</institution>
				<degree_type>Master's</degree_type>
				<specialization>Computer Science</specialization>
			</degree>
			<degree>
				<date_awarded>1987</date_awarded>
				<institution>Università di Bologna, Italy</institution>
				<degree_type>Laurea</degree_type>
				<specialization>Physics</specialization>
			</degree>
		</degrees>
		<office_hours>
			<meeting_time_and_place>
				<start_time>16:00:00</start_time>
				<end_time>17:00:00</end_time>
				<location>
					<building>
						<abbreviation>ACES</abbreviation>
						<long_name>Applied Computational Engineering and Sciences Building</long_name>
					</building>
					<room>6.244</room>
				</location>
				<days>
					<day>Tuesday</day>
					<day>Thursday</day>
				</days>
			</meeting_time_and_place>
		</office_hours>
		<classes>
			<class>
				<unique_number>54375</unique_number>
				<name>Distributed Computing</name>
				<description>Models of distributed systems; language issues, proving properties of distributed systems; time, clocks, partial ordering of events; deadlock and termination detection; diffusing computations; computing in hostile environments; distributed resource management.</description>
				<course_number>
					<field_of_study>CS</field_of_study>
					<number>380D</number>
				</course_number>
				<semester>Spring</semester>
				<year>2010</year>
				<teaching_assistants>
					<name>
						<first_name>Apurv</first_name>
						<last_name>Bhartia</last_name>
					</name>
				</teaching_assistants>
				<meeting_times_and_places>
					<meeting_time_and_place>
						<start_time>17:00:00</start_time>
						<end_time>18:30:00</end_time>
						<location>
							<building>
								<abbreviation>RLM</abbreviation>
								<long_name>Robert Lee Moore</long_name>
							</building>
							<room>5.126</room>
						</location>
						<days>
							<day>Tuesday</day>
							<day>Thursday</day>
						</days>
					</meeting_time_and_place>
				</meeting_times_and_places>
			</class>
		</classes>
		<journal_articles>
			<article>
				<journal>ACM Trasactions on Computer Systems</journal>
				<title>Zyzzyva: Speculative Byzantine Fault Tolerance</title>
				<issue_date>2009-12</issue_date>
				<other_authors>
					<name>
						<first_name>R.</first_name>
						<last_name>Kotla</last_name>
					</name>
					<name>
						<first_name>A.</first_name>
						<last_name>Clement</last_name>
					</name>
					<name>
						<first_name>E.</first_name>
						<last_name>Wong</last_name>
					</name>
					<name>
						<first_name>M.</first_name>
						<last_name>Dahlin</last_name>
					</name>
				</other_authors>
			</article>
		</journal_articles>
		<conferences>
			<conference>
				<date>2009-11</date>
				<name>The 11th International Symposium on Stabilization, Safety, and Security of Distributed Systems (SSS 2009)</name>
				<location>Lyon, France</location>
				<presentation_title>Model Checking Coalition Nash Equilibria in MAD Distributed Systems</presentation_title>
			</conference>
		</conferences>
		<grad_students>
			<grad_student>
				<name>
					<first_name>Amitanand</first_name>
					<middle_name>S.</middle_name>
					<last_name>Aiyer</last_name>
				</name>
				<type>Ph.D.</type>
				<writings></writings>
			</grad_student>
		</grad_students>
	</faculty_member>
	<faculty_member> <!-- Inderjit S. Dhillon -->
		<name>
			<first_name>Inderjit</first_name>
			<middle_name>S.</middle_name>
			<last_name>Dhillon</last_name>
		</name>
		<faculty_type>Professor</faculty_type>
		<office>
			<building>
				<abbreviation>ACES</abbreviation>
				<long_name>Applied Computational Engineering and Sciences Building</long_name>
			</building>
			<room>2.332</room>
		</office>
		<email_addresses>
			<email>inderjit@cs.utexas.edu</email>
		</email_addresses>
		<websites>
			<website>http://userweb.cs.utexas.edu/~inderjit/</website>
		</websites>
		<phone_numbers>
			<phone_number>
				<phone_type>department</phone_type>
				<area_code>512</area_code>
				<number>4717316</number>
			</phone_number>
			<phone_number>
				<phone_type>work</phone_type>
				<area_code>512</area_code>
				<number>4719725</number>
			</phone_number>
			<phone_number>
				<phone_type>fax</phone_type>
				<area_code>512</area_code>
				<number>4718885</number>
			</phone_number>
		</phone_numbers>
		<classes>
			<class>
				<unique_number>54340</unique_number>
				<name>Introduction to Data Mining</name>
				<description>Only one of the following may be counted unless the topics vary: Computer Sciences 178, 378, 178H, 378H.</description>
				<course_number>
					<field_of_study>CS</field_of_study>
					<number>378</number>
				</course_number>
				<semester>Spring</semester>
				<year>2010</year>
				<meeting_times_and_places>
					<meeting_time_and_place>
						<start_time>09:30:00</start_time>
						<end_time>11:00:00</end_time>
						<location>
							<building>
								<abbreviation>TAY</abbreviation>
								<long_name>Taylor Hall</long_name>
							</building>
							<room>3.144</room>
						</location>
						<days>
							<day>Tuesday</day>
							<day>Thursday</day>
						</days>
					</meeting_time_and_place>
				</meeting_times_and_places>
			</class>
		</classes>
		<research_areas>
			<research_area>Data mining</research_area>
			<research_area>Machine learning</research_area>
			<research_area>Numerical linear algebra</research_area>
			<research_area>Scientific computing</research_area>
			<research_area>Numerical Optimization</research_area>
			<research_area>Bioinformatics</research_area>
		</research_areas>
		<degrees>
			<degree>
				<date_awarded>1989</date_awarded>
				<institution>Indian Institute of Technology at Bombay</institution>
				<degree_type>B. Tech</degree_type>
				<specialization>Computer Science and Engineering</specialization>
			</degree>
			<degree>
				<date_awarded>1997</date_awarded>
				<institution>University of California at Berkeley</institution>
				<degree_type>Ph.D.</degree_type>
				<specialization>Computer Science</specialization>
			</degree>
		</degrees>
		<published_books>
			<book>
				<title>ScaLAPACK Users’ Guide</title>
				<publisher>SIAM</publisher>
				<date_published>1997</date_published>
				<other_authors>
					<name>
						<first_name>L.</first_name>
						<last_name>Blackford</last_name>
					</name>
					<name>
						<first_name>J.</first_name>
						<last_name>Choi</last_name>
					</name>
					<name>
						<first_name>A.</first_name>
						<last_name>Cleary</last_name>
					</name>
					<name>
						<first_name>E.</first_name>
						<last_name>D'Azevedo</last_name>
					</name>
					<name>
						<first_name>J.</first_name>
						<last_name>Demmel</last_name>
					</name>
					<name>
						<first_name>J.</first_name>
						<last_name>Dongarra</last_name>
					</name>
					<name>
						<first_name>S.</first_name>
						<last_name>Hammarling</last_name>
					</name>
					<name>
						<first_name>G.</first_name>
						<last_name>Henry</last_name>
					</name>
					<name>
						<first_name>A.</first_name>
						<last_name>Petitet</last_name>
					</name>
					<name>
						<first_name>K.</first_name>
						<last_name>Stanley</last_name>
					</name>
					<name>
						<first_name>R.</first_name>
						<last_name>Whaley</last_name>
					</name>
					<name>
						<first_name>D.</first_name>
						<last_name>Walker</last_name>
					</name>
				</other_authors>
			</book>
		</published_books>
		<journal_articles>
			<article>
				<journal>Journal of Machine Learning Research(JMLR)</journal>
				<title>Low-Rank Kernel Learning with Bregman Matrix Divergences</title>
				<issue_date>2009-02</issue_date>
				<other_authors>
					<name>
						<first_name>B.</first_name>
						<last_name>Kuhlis</last_name>
					</name>
					<name>
						<first_name>M.</first_name>
						<last_name>Sustik</last_name>
					</name>
				</other_authors>
			</article>
		</journal_articles>
		<conferences>
			<conference>
				<date>2009-12</date>
				<name>Neural Information Processing Systems Conference (NIPS)</name>
				<location>Vancouver, Canada</location>
				<presentation_title>Matrix Completion from Power-Law Distributed Samples</presentation_title>
			</conference>
		</conferences>
		<grad_students>
			<grad_student>
				<name>
					<first_name>Dongmin</first_name>
					<last_name>Kim</last_name>
				</name>
				<type>Ph.D.</type>
			</grad_student>
		</grad_students>
	</faculty_member>
	<faculty_member> <!-- Warren A. Hunt, Jr. -->
		<name>
			<first_name>Warren</first_name>
			<middle_name>A.</middle_name>
